services:
    ollama:
        volumes:
            - ./ollama_data:/root/.ollama
        container_name: local-ollama
        ports:
            - "${OLLAMA_PORT}:11434"
        image: ollama/ollama:latest
        restart: unless-stopped
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]

    mind-map-meadow:
        build:
            context: ./mind-map-meadow
            dockerfile: Dockerfile
        container_name: game-meadow
        ports:
            - "${GAME_SERVER_PORT}:5000"
            - "${VITE_DEV_PORT}:5173"
        environment:
            - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DB}
            - VITE_WATCH=true
        volumes:
            - ./mind-map-meadow:/app
            - /app/node_modules
            - /app/dist
        command: npm run dev
        restart: unless-stopped
        depends_on:
            - postgres-db
            - ollama

    postgres-db:
        image: pgvector/pgvector:pg16
        container_name: meadow-db
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        ports:
            - "${POSTGRES_PORT}:5432"
        restart: unless-stopped

    db-viewer:
        image: adminer:latest
        container_name: meadow-db-viewer
        ports:
            - "${DB_VIEWER_PORT}:8080"
        restart: unless-stopped
        depends_on:
            - postgres-db
